FROM python:3.7-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    HADOOP_HOME=/opt/hadoop \
    PATH="/opt/hadoop/bin:/opt/hadoop/sbin:${PATH}"

# =====================
# Dependencias base
# =====================

RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    curl \
    gcc \
    g++ \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# =====================
# Hadoop Client
# =====================

RUN curl -L https://archive.apache.org/dist/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz \
    | tar -xz -C /opt \
    && mv /opt/hadoop-3.2.1 /opt/hadoop

# =====================
# Python deps
# =====================

WORKDIR /producer

RUN pip install --no-cache-dir \
    pandas \
    numpy \
    pyarrow \
    pickle-mixin

# =====================
# Copiar código
# =====================

COPY ./producer /producer

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

CMD ["python", "/producer/producer.py"]
